# Generated by Django 5.0.1 on 2024-02-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_des',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_title',
            field=models.CharField(max_length=50),
        ),
    ]
